### ISSUE TITLE
Hello, dear developer, I accidentally made a mistake, can you help me?

### ISSUE THREAD

**Issue by dollars2021** [JackHamer09/zkExport#1]
Hello dear developer, I accidentally made a mistake, https://zkexport.netlify.app/ in there，
First I experienced our product, I thought it was great, then I saw that the upper right corner can help builders to buy a cup of coffee
donate to this address 0x11Ed0AC7D6142481E459B6e5d4bfB5646277796f， 

I want to donate 1usd to the builder, but I accidentally made a mistake and donated all my balance. This is the donation record
0xb595b29d7591d1e8f443aaab18a3e7767411abc187b20ecb2ab326cf436293a0

This is all my property, can you help me return it? Return to my original donation address

Is it okay to keep 10 usd as my donation?

Dear sir, I hope you can see this message as soon as possible, because this is all my money, I hope you can help me

**Comment by JackHamer09** [comment]
Sure man, no problems at all
Sent you 0.1 ETH back
https://zkscan.io/explorer/transactions/0x95e58c1bd0f64c0de1a8cfd54132855a8291d8acfddb222a0d9df959c990c954
